version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - network.publish_host=192.168.1.15
      - cluster.initial_master_nodes=192.168.1.15,192.168.1.16
      - discovery.seed_hosts=192.168.1.16
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - node.master=true
      - node.data=true  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
      - /data/log/elasticsearch:/var/log/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300  
      
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - network.publish_host=192.168.1.16
      - network.host=0.0.0.0
      - discovery.seed_hosts=192.168.1.15
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=192.168.1.15,192.168.1.16 
      - node.master=true
      - node.data=true  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300  
